/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cowindesktop.linearactuator;

import javax.swing.*;
import java.awt.*;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import com.fazecast.jSerialComm.*;
import java.io.*;
/**
 *
 * @author PHANEENDRA
 */
public class linearActuatorGUI extends javax.swing.JFrame {

    SerialPort serialPort1;
    OutputStream outputStream1;
     String dataBuffer="";
    /**
     * Creates new form linearActuatorGUI
     */
    public linearActuatorGUI() {
        initComponents();
        
        comport_jComboBox.setEnabled( true );
        connect_jButton.setEnabled( true );
        disconnect_jButton.setEnabled( false );
        setDistance_jButton.setEnabled( false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        connect_jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comport_jComboBox = new javax.swing.JComboBox<>();
        baudRate_jComboBox = new javax.swing.JComboBox<>();
        disconnect_jButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        setDistance_jButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        setDistance_jSlider = new javax.swing.JSlider();
        setDistance_jLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        currentDistance_jLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        connect_jButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        connect_jButton.setText("Connect");
        connect_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_jButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel1.setText("COM PORT");

        comport_jComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comport_jComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });

        baudRate_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4800", "9600", "19200", "38400", "57600", "115200" }));
        baudRate_jComboBox.setSelectedIndex(1);

        disconnect_jButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disconnect_jButton.setText("Disconnect");
        disconnect_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_jButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jLabel2.setText("BAUD RATE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(connect_jButton)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(baudRate_jComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE)
                            .addComponent(comport_jComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(disconnect_jButton)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comport_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(baudRate_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connect_jButton)
                    .addComponent(disconnect_jButton))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDistance_jButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setDistance_jButton.setText("Update");
        setDistance_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDistance_jButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Set Distance");

        setDistance_jSlider.setMaximum(95);
        setDistance_jSlider.setMinimum(10);
        setDistance_jSlider.setValue(10);
        setDistance_jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setDistance_jSliderStateChanged(evt);
            }
        });

        setDistance_jLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        setDistance_jLabel.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Current Distance");

        currentDistance_jLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        currentDistance_jLabel.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText(":");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setDistance_jButton)
                    .addComponent(setDistance_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setDistance_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentDistance_jLabel))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(currentDistance_jLabel)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(setDistance_jLabel))
                .addGap(18, 18, 18)
                .addComponent(setDistance_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(setDistance_jButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel7.setText("Linear Actuator");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel8.setText("Controller");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connect_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_jButtonActionPerformed
try {
        // Get selected serial port
        SerialPort[] portLists = SerialPort.getCommPorts();
        serialPort1 = portLists[comport_jComboBox.getSelectedIndex()];

        // Set serial port parameters
        int selectedBaudRate = Integer.parseInt(baudRate_jComboBox.getSelectedItem().toString());
        serialPort1.setBaudRate(selectedBaudRate);
        serialPort1.setNumDataBits(8);
        serialPort1.setNumStopBits(1);
        serialPort1.setParity(SerialPort.NO_PARITY);

        // Open the serial port
        serialPort1.openPort();
        
        JOptionPane.showMessageDialog(this, serialPort1.getDescriptivePortName() + " Success");
        comport_jComboBox.setEnabled(true);
        connect_jButton.setEnabled(false);
        disconnect_jButton.setEnabled(true);
        setDistance_jButton.setEnabled( true );
        
        try (OutputStream outputStream = serialPort1.getOutputStream()) {
            
            if (serialPort1.isOpen()) {
                
                // Send data
                String dataToSend = "$72,1124,1,#\r\n";
                try {
                    outputStream.write(dataToSend.getBytes());
                    Serial_EventBasedReading(serialPort1, new DataReceivedCallback() {
                    @Override
                    public void onDataReceived(String data) {
                    String currDist="";
                    currDist+=data.charAt(4);
                    currDist+=data.charAt(5);
                    currentDistance_jLabel.setText(currDist);
                  }
                });

                    
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }  

            } else {
                JOptionPane.showMessageDialog(this, serialPort1.getDescriptivePortName() + " Failure");
            }
        } 

        
    } catch (ArrayIndexOutOfBoundsException a) {
        JOptionPane.showMessageDialog(this, "Choose COM PORT", "ERROR", ERROR_MESSAGE);
    } catch (Exception b) {
        JOptionPane.showMessageDialog(this, "ERROR", "ERROR", ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_connect_jButtonActionPerformed

    private void disconnect_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnect_jButtonActionPerformed
        // TODO add your handling code here:
        disconnect_jButton.setEnabled( false );
        setDistance_jButton.setEnabled( false );
        currentDistance_jLabel.setText("0");
        setDistance_jLabel.setText("0");
        setDistance_jSlider.setValue(0);
        if(serialPort1.isOpen()){
            serialPort1.closePort();
            connect_jButton.setEnabled( true );
        }
    }//GEN-LAST:event_disconnect_jButtonActionPerformed

    private void comport_jComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comport_jComboBoxPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        comport_jComboBox.removeAllItems();
        SerialPort []portLists = SerialPort.getCommPorts();
        for(SerialPort port : portLists){
            comport_jComboBox.addItem(port.getSystemPortName());
        }
    }//GEN-LAST:event_comport_jComboBoxPopupMenuWillBecomeVisible

    private void setDistance_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDistance_jButtonActionPerformed
        // TODO add your handling code here:
        OutputStream outputStream = serialPort1.getOutputStream();
                if (serialPort1.isOpen()) {
                
                // Send data "$71,1124,10,1,#\r\n"
                String datToSendFront="$71,1124,";
                String datToSendBack=",1,#\r\n";
                String dataToSend = datToSendFront+String.valueOf(setDistance_jSlider.getValue())+datToSendBack;
                try {
                    outputStream.write(dataToSend.getBytes());
                    Serial_EventBasedReading(serialPort1, new DataReceivedCallback() {
                    @Override
                    public void onDataReceived(String data) {
                    String currDist="";
                    currDist+=data.charAt(4);
                    currDist+=data.charAt(5);
                    currentDistance_jLabel.setText(currDist);
                  }
                });
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }  

            } else {
                JOptionPane.showMessageDialog(this, serialPort1.getDescriptivePortName() + " Failure");
            }
    }//GEN-LAST:event_setDistance_jButtonActionPerformed

    private void setDistance_jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_setDistance_jSliderStateChanged
        // TODO add your handling code here:
         setDistance_jLabel.setText(String.valueOf(setDistance_jSlider.getValue()));
    }//GEN-LAST:event_setDistance_jSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public interface DataReceivedCallback {
    void onDataReceived(String data);
    }
    
    private void Serial_EventBasedReading(SerialPort activePort, DataReceivedCallback callback){

activePort.addDataListener(new SerialPortDataListener() {
        @Override
        public int getListeningEvents() {
            return SerialPort.LISTENING_EVENT_DATA_RECEIVED;
        }

        @Override
        public void serialEvent(SerialPortEvent event) {
            byte[] newData = event.getReceivedData();

            StringBuilder dataBuffer = new StringBuilder();
            for (int i = 0; i < newData.length; i++) {
                dataBuffer.append((char) newData[i]);
            }

//            SwingUtilities.invokeLater(new Runnable() {
//                @Override
//                public void run() {
//                    receive_jTextArea.setText(dataBuffer.toString());
//                }
//            });

            if (callback != null) {
                callback.onDataReceived(dataBuffer.toString());
            }
        }
    });
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(linearActuatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(linearActuatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(linearActuatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(linearActuatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new linearActuatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> baudRate_jComboBox;
    private javax.swing.JComboBox<String> comport_jComboBox;
    private javax.swing.JButton connect_jButton;
    private javax.swing.JLabel currentDistance_jLabel;
    private javax.swing.JButton disconnect_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton setDistance_jButton;
    private javax.swing.JLabel setDistance_jLabel;
    private javax.swing.JSlider setDistance_jSlider;
    // End of variables declaration//GEN-END:variables
}
